-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.dim_conglomerado
(
    id serial NOT NULL,
    institution_cnpj character varying COLLATE pg_catalog."default",
    institution_name character varying COLLATE pg_catalog."default",
    conglomerate_cnpj character varying COLLATE pg_catalog."default",
    name character varying COLLATE pg_catalog."default",
    CONSTRAINT dim_conglomerado_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.dim_empresa
(
    id serial NOT NULL,
    cnpj character varying COLLATE pg_catalog."default",
    bacen_status character varying COLLATE pg_catalog."default",
    entity_type character varying COLLATE pg_catalog."default",
    legal_status character varying COLLATE pg_catalog."default",
    consolidation_type character varying COLLATE pg_catalog."default",
    control_type character varying COLLATE pg_catalog."default",
    registration_date character varying COLLATE pg_catalog."default",
    date_end character varying COLLATE pg_catalog."default",
    is_conglomerate_leader boolean,
    name character varying COLLATE pg_catalog."default",
    trade_name character varying COLLATE pg_catalog."default",
    CONSTRAINT dim_empresa_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.dim_endereco
(
    id serial NOT NULL,
    cnpj character varying COLLATE pg_catalog."default",
    address_type character varying COLLATE pg_catalog."default",
    registration_date date,
    date_end date,
    street character varying COLLATE pg_catalog."default",
    complement character varying COLLATE pg_catalog."default",
    "number" integer,
    neighborhood character varying COLLATE pg_catalog."default",
    city character varying COLLATE pg_catalog."default",
    state character varying COLLATE pg_catalog."default",
    postalcode character varying COLLATE pg_catalog."default",
    branch_code character varying COLLATE pg_catalog."default",
    CONSTRAINT dim_endereco_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.fato_receita_lucro
(
    id serial NOT NULL,
    cnpj character varying COLLATE pg_catalog."default",
    address_id integer,
    company_id integer,
    conglomerate_id integer,
    date date,
    credit_operations_revenue numeric,
    leasing_operations_revenue numeric,
    tvm_operations_revenue numeric,
    derivatives_operations_revenue numeric,
    foreign_exchange_operations_revenue numeric,
    compulsory_applications_revenue numeric,
    service_provision_revenue numeric,
    bank_fee_revenue numeric,
    other_operating_revenues numeric,
    net_income numeric,
    CONSTRAINT fato_receita_lucro_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.fato_receita_lucro
    ADD CONSTRAINT fato_receita_lucro_conglomerado_id_fkey FOREIGN KEY (conglomerate_id)
    REFERENCES public.dim_conglomerado (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.fato_receita_lucro
    ADD CONSTRAINT fato_receita_lucro_empresa_id_fkey FOREIGN KEY (company_id)
    REFERENCES public.dim_empresa (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.fato_receita_lucro
    ADD CONSTRAINT fato_receita_lucro_endereco_id_fkey FOREIGN KEY (address_id)
    REFERENCES public.dim_endereco (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;